plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractHibernateMappingExporterFacade.java
plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractPersistentClassFacade.java
plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IPersistentClass.java

Multiple issues found while looking into this.
. `IPersistentClass` had setAbstract(boolean) instead of
setAbstract(Boolean)
. Call to `exportPojo` was done with wrong argument types and count.
I fear there might be more but this patch seem to at least make the
situation better as opposed to worse since the code could never have
worked with the current logic.
Signed-off-by: Max Rydahl Andersen <manderse@redhat.com>

JBIDE-20042 Cannot generate hbm.xml from java class

---

plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractFacadeFactory.java
plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/IFacadeFactory.java
tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/FacadeFactoryTest.java
tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryTest.java

JBIDE-25132: Remove interface 'org.jboss.tools.hibernate.runtime.spi.IMappings' - Remove unused method IFacadeFactory#createMappings(Object)

---

hibernate-search-tests/org.jboss.tools.hibernate.search.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Edit '.gitignore' to include generated '.classpath', '.project' and '.settings/'

---

features/org.hibernate.eclipse.test.feature/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'features/org.hibernate.eclipse.test.feature/.gitignore' file

---

features/org.jboss.tools.hibernate.search.test.feature/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'features/org.jboss.tools.hibernate.search.test.feature/.gitignore' file

---

hibernate-search-plugins/org.jboss.tools.hibernate.search/META-INF/MANIFEST.MF
hibernate-search-plugins/org.jboss.tools.hibernate.search/build.properties

JBIDE-25284: Use default plugin classpath in 'org.jboss.tools.hibernate.search'

---

hibernate-search-plugins/org.jboss.tools.hibernate.search/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'hibernate-search-plugins/org.jboss.tools.hibernate.search/.gitignore' file

---

hibernate-search-plugins/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'hibernate-search-plugins/.gitignore' file

---

plugins/org.hibernate.eclipse/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.hibernate.eclipse/.gitignore' file

---

plugins/org.hibernate.eclipse.console/META-INF/MANIFEST.MF
plugins/org.hibernate.eclipse.console/build.properties

JBIDE-25290: Use default plugin classpath in 'org.hibernate.eclipse.console'

---

plugins/org.hibernate.eclipse.console/.gitignore

 JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.hibernate.eclipse.console/.gitignore' file

---

plugins/org.hibernate.eclipse.mapper/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.hibernate.eclipse.mapper/.gitignore' file

---

plugins/org.jboss.tools.hibernate.jpt.core/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.jpt.core/.gitignore' file

---

plugins/org.jboss.tools.hibernate.jpt.ui/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.jpt.ui/.gitignore' file

---

plugins/org.jboss.tools.hibernate.libs.dom4j.v_1_6_1/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.libs.dom4j.v_1_6_1/.gitignore' file

---

plugins/org.jboss.tools.hibernate.libs.freemarker.v_2_3_8/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.libs.freemarker.v_2_3_8/.gitignore' file

---

plugins/org.jboss.tools.hibernate.runtime.common/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.runtime.common/.gitignore' file

---

plugins/org.jboss.tools.hibernate.runtime.v_3_5/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.runtime.v_3_5/.gitignore' file

---

plugins/org.jboss.tools.hibernate.runtime.v_4_0/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.runtime.v_4_0/.gitignore' file

---

plugins/org.jboss.tools.hibernate.runtime.v_4_3/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.runtime.v_4_3/.gitignore' file

---

plugins/org.jboss.tools.hibernate.runtime.v_5_0/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.runtime.v_5_0/.gitignore' file

---

plugins/org.jboss.tools.hibernate.xml.ui/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'plugins/org.jboss.tools.hibernate.xml.ui/.gitignore' file

---

tests/org.hibernate.eclipse.console.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.hibernate.eclipse.console.test/.gitignore' file

---

tests/org.hibernate.eclipse.jdt.ui.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.hibernate.eclipse.jdt.ui.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.jpt.core.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.jpt.core.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.runtime.v_3_6.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.runtime.v_3_6.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.runtime.v_4_0.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.runtime.v_4_0.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.runtime.v_4_3.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.runtime.v_4_3.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.runtime.v_5_0.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.runtime.v_5_0.test/.gitignore' file

---

tests/org.jboss.tools.hibernate.runtime.v_5_1.test/.gitignore

JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'tests/org.jboss.tools.hibernate.runtime.v_5_1.test/.gitignore' file

---

plugins/org.hibernate.eclipse.jdt.ui/build.properties

JBIDE-25372: Remove 'plugin.properties' from 'src.includes' in plugin 'org.hibernate.eclipse.jdt.ui'

---

hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.spi/build.properties

JBIDE-25282: Clean up 'build.properties' in 'org.jboss.tools.hibernate.search.runtime.spi'

---

plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/utils/ProjectUtils.java
plugins/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/internal/HQLExpressionCompilerParticipant.java
plugins/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/internal/jpa/actions/JPAMapToolActor.java
plugins/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/internal/jpa/common/Utils.java
tests/org.hibernate.eclipse.jdt.ui.test/src/org/hibernate/eclipse/jdt/ui/test/JPAMapTest.java

JBIDE-25749: Replace uses of deprecated field AST.JLS8 by AST.JLS9 in class org.eclipse.jdt.core.dom.AST

---

tests/org.jboss.tools.hibernate.runtime.spi.test/build.properties

JBIDE-25764: Remove warning in build.properties of org.jboss.tools.hibernate.runtime.spi.test

---

tests/org.jboss.tools.hibernate.runtime.v_5_0.test/META-INF/MANIFEST.MF

JBIDE-25827: Update plugin execution environment of 'org.jboss.tools.hibernate.runtime.v_5_0.test' to 'JavaSE-1.8'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java
tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/CoreMappingTestHelper.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Disable CoreMappingTest#testOpenMappingFile()

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Disable CoreMappingTest completely

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.any' and 'core.version.db'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.cid' and 'core.unionsubclass2'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.cuk' and 'core.sql.check'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.cut' and 'core.sorted'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.deletetransient' and 'core.rowid'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.filter' and 'core.pagination'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.formulajoin' and 'core.orphan'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.idclass' and 'core.onetoone.link'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.interfaceproxy' and 'core.mixed'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.join and 'core.mapcompelem'

---

tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/CoreMappingTest.java

JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9 - Enable test for packages 'core.joinedsubclass' and 'core.map'

---

tests/org.jboss.tools.hibernate.orm.test/META-INF/MANIFEST.MF

Add support for Hibernate 5.4 - Make the tests in 'org.jboss.tools.hibernate.orm.test' run with 5.4

---

features/org.hibernate.eclipse.test.feature/feature.xml
tests/org.jboss.tools.hibernate.runtime.v_5_4.test/META-INF/MANIFEST.MF

JBIDE-26498 - coretests failing because of an hibernate dependency missing

---

plugins/org.jboss.tools.hibernate.runtime.v_5_4/META-INF/MANIFEST.MF
plugins/org.jboss.tools.hibernate.runtime.v_5_4/pom.xml

JBIDE-26511: Update byte buddy version to 1.9.5 in org.jboss.tools.hibernate.runtime.v_5_4

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add dependency for Hibernate Tools ORM 6.0.0.Alpha1

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#getProperty(String)'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#addProperties(Properties)'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#preferBasicCompositeIds()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testSetPreferBasicCompositeIds()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'GenericExporterFacadeImpl#getTemplateName()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createGenericExporter(Object)'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest#testGetGenericExporter()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest#testGetHbm2DDLExporter()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFactoryFacadeTest#testGetCollectionMetadata()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/DummyMetadataBuildingContext.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/DummyMetadataBuildingContextTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement class 'DummyMetadataBuildingContext'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetFetchModeJoin()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/build.properties

JBIDE-27580: Update dependency of the runtime tests on H2 to version 1.4.200 - Fix runtime for org.jboss.tools.hibernate.runtime.v_5_4.test

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/build.properties

JBIDE-27580: Update dependency of the runtime tests on H2 to version 1.4.200 - Fix runtime for org.jboss.tools.hibernate.runtime.v_x_y.test

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ForeignKeyFacadeTest#testGetReferencedTable()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ForeignKeyFacadeTest#testIsReferenceToPrimaryKey()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ForeignKeyFacadeTest#testGetReferencedColumns()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of HibernateMappingExporterFacadeTest#testGetOutputDirectory()

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of HibernateMappingExporterFacadeTest#testSetOutputDirectory()

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryImpl#createForeignKey(Object)'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetReplaceStart()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetCompletionKind()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetEntityName()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCodeAssistFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCodeAssistFacadeTest#testCodeComplete()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetRootClass()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetPropertyClosureIterator()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetIdentifier()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractPersistentClassFacade.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetParentProperty()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetSubclassIterator()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetDiscriminatorValue()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetRootTable()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testGetColumns()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testGetColumn()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testGetTable()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetPropetyAccessorName()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#ttestSetPropertyAccessorName()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#ttestIsOptimisticLocked()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryExporterFacadeTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'QueryExporterFacadeTest#setQueries()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newJDBCMetaDataConfiguration()'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/DummyMetadataDescriptor.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/DummyMetadataDescriptorTest.java

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'DummyMetadataDescriptorTest#testGetProperties()'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java

JBIDE-27775: Use JUnit Jupiter instead of JUnit 4 - Switch test class 'org.jboss.tools.hibernate.runtime.v_6_0.VersionTest'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ArtifactCollectorFacadeTest.java

JBIDE-27775: Use JUnit Jupiter instead of JUnit 4 - Switch test class 'org.jboss.tools.hibernate.runtime.v_6_0.internal.ArtifactCollectorFacadeTest'

---

orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/node/PersistentCollectionNode.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractTypeFacade.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IType.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/TypeFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java

JBIDE-27823: Replace uses of 'org.jboss.tools.hibernate.runtime.spi.IType#getReturnedClass()' - Remove from runtime tests

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManagerTest.java

JBIDE-27839: Use the preferences mechanism to read/save the default Hibernate runtime - Prevent disabling the default runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManagerTest.java

JBIDE-27839: Use the preferences mechanism to read/save the default Hibernate runtime - Implement 'RuntimeServiceManager#setDefaultVersion(String)'

---

.github/workflows/build_test.yml
features/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/TypeFactoryFacadeTest.java

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

fix tests path

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractQueryExporterFacade.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/QueryExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/QueryExporterFacadeTest.java

JBIDE-27854: Fix typo in class 'org.jboss.tools.hibernate.runtime.common.AbstractQueryExporterFacade#setFilename(String)'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/META-INF/MANIFEST.MF

JBIDE-27351: Set up a runtime plugin for the upcoming Hibernate 5.5.x releases - Remove unneeded dependency on the dom4j library

---

orm/test/core/org.jboss.tools.hibernate.orm.test/META-INF/MANIFEST.MF

JBIDE-27907: Switch Hibernate core dependency of test plugin 'org.jboss.tools.hibernate.orm.test' from 5.4 to 5.5

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28045: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.0.Beta2

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28057: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.0.CR1

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml

JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Remove unneeded dependency on 'com.sun.istack.istack-commons-runtime'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28168: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.1.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ArtifactCollectorFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ForeignKeyFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/GenericExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/Hbm2DDLExporterFacadeTest.java

JBIDE-28170: Remove the unneeded dependency on javassist from the 5.4 runtime implementation and rework the relevant unit tests

---

orm/test/core/org.jboss.tools.hibernate.orm.test/META-INF/MANIFEST.MF

JBIDE-28171: Use the 5.6 runtime to run the tests in 'org.jboss.toolshibernate.orm.test'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/META-INF/MANIFEST.MF

JBIDE-28092: Update the execution environment of the JBoss Tools plugins to Java 11 - Perform changes for org.jboss.tools.hibernate.runtime.v_5_1.test

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java

JBIDE-28198: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.24.Final

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/META-INF/MANIFEST.MF

JBIDE-28190: Improve the tests of the 5.1 runtime plugin - Remove unneeded plugin dependency on 'org.junit'

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/META-INF/MANIFEST.MF

JBIDE-28200: Add the tests of the 5.0 runtime plugin - Remove unneeded plugin dependency on 'org.junit'

---

orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/ProjectCompilerVersionChecker.java
orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/ExportImageActionTest.java
orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/JPAMapMockTest.java
orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/OrmDiagramTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ArtifactCollectorFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/FacadeFactoryTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ForeignKeyFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/GenericExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/Hbm2DDLExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/OverrideRepositoryFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ArtifactCollectorFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/FacadeFactoryTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ForeignKeyFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/GenericExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/Hbm2DDLExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/OverrideRepositoryFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ArtifactCollectorFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ForeignKeyFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/GenericExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/Hbm2DDLExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ArtifactCollectorFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ForeignKeyFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/GenericExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/Hbm2DDLExporterFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SchemaExportFacadeTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SessionFactoryFacadeTest.java

JBIDE-28083: Hibernate Java 17 compability - Add the JDK15, JDK16 and JDK17 options to the ProjectCompilerVersionChecker switch

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_5.test/src/org/jboss/tools/hibernate/runtime/v_5_5/VersionTest.java

JBIDE-28273: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_5 to version 5.5.9.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/VersionTest.java

JBIDE-28276: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_2 to version 5.2.13.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/META-INF/MANIFEST.MF

JBIDE-28092: Update the execution environment of the JBoss Tools plugins to Java 11 - Perform changes for org.jboss.tools.hibernate.runtime.v_4_3

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28292: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.3.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28312: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.4.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/META-INF/MANIFEST.MF

JBIDE-28295: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_4_3' - Cleanup 'MANIFEST.MF' file

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/VersionTest.java

JBIDE-28316: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_4_3 to version 4.3.6.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/pom.xml

JBIDE-28313: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_4_0' - Some cleanup

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/pom.xml

JBIDE-28340: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_6' - Remove the Maven dependency on 'log4j:log4j:1.2.15'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/VersionTest.java

JBIDE-28352: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_3_6 to version 3.6.2.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/pom.xml

JBIDE-28340: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_6' - Remove the unneeded Maven dependency on 'asm:asm:3.1'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/pom.xml

JBIDE-28340: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_6' - Remove the unneeded Maven dependency on 'cglib:cglib:2.2'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/pom.xml

JBIDE-28349: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_5' - Remove the unneeded Maven dependency on 'asm:asm:3.1'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/pom.xml

JBIDE-28349: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_5' - Remove unneeded Maven dependency on 'log4j:log4j:1.2.15'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/VersionTest.java

JBIDE-28364: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_3_5 to version 3.5.3.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/pom.xml

JBIDE-28349: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_5' - Remove unneeded Maven dependency on 'cglib:cglib:2.2'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/pom.xml

JBIDE-28349: Remove the Maven dependencies for 'org.jboss.tools.hibernate.runtime.v_3_5' - Remove unneeded Maven dependency on 'asm:asm:3.1'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java

JBIDE-28453: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_0 to version 6.0.0.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28457: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.8.Final

---

orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizard.java

JBIDE-27954: Creating Hibernate Console Configuration is not completely successful when not navigating to cfg.xml creation page

---

orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizardPage.java

JBIDE-28156: The default Hibernate runtime should appear as the default choice at Hibernate console and configuration creation

---

common/plugin/lib/org.jboss.tools.hibernate.libs.jboss-logging.v_3_4/META-INF/MANIFEST.MF
common/plugin/lib/org.jboss.tools.hibernate.libs.jboss-logging.v_3_4/pom.xml

JBIDE-28468: Update Maven dependency of 'org.jboss.tools.hibernate.libs.jboss-logging.v_3_4' to version 3.4.3.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCodeAssistFacadeTest.java

JBIDE-28483: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_0 to version 6.0.1.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28488: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.9.Final

---

common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/META-INF/MANIFEST.MF
common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/build.properties
common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/pom.xml

JBIDE-28512: Update dependency of 'org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10' on 'org.antlr:antlr4-runtime' to version 4.10.1

---

orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizard.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractService.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IService.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ServiceImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ServiceImplTest.java

JBIDE-28604: Add method IService#createCfgExporter() to remove explicit class naming of 'org.hibernate.tool.hbm2x.HibernateConfigurationExporter'

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28609: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.10.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java

JBIDE-28660: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_1 to version 6.1.2.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28661: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.11.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java

JBIDE-28667: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_1 to version 6.1.3.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28668: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.12.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java

JBIDE-28710: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_1 to version 6.1.4.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java

JBIDE-28737: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.13.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java

JBIDE-28743: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.28.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/MetadataHelper.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/MetadataHelperTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.util.MetadataHelperTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.util.MetadataHelper'
- Add dependency on 'org.jboss.tools.hibernate.libs.jaxb.v_3_0'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - MetadataHelper

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/JdbcMetadataConfiguration.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/JdbcMetadataConfigurationTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.util.JdbcMetadataConfigurationTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.util.JdbcMetadataConfiguration'
- Add dependency on 'org.jboss.tools.hibernate.libs.h2.v_2_1'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - JdbcMetadataConfiguration

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/ConfigurationMetadataDescriptor.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/util/ConfigurationMetadataDescriptorTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.util.ConfigurationMetadataDescriptorTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.util.ConfigurationMetadataDescriptor'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ConfigurationMetadataDescriptor

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ForeignKeyFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ForeignKeyFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ForeignKeyFacadeTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.ForeignKeyFacadeImpl'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ForeignKeyFacade

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/GenericExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/GenericExporterFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.GenericExporterFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.GenericExporterFacadeImpl'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - GenericExporterFacade

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/Hbm2DDLExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/Hbm2DDLExporterFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.Hbm2DDLExporterFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.Hbm2DDLExporterFacadeImpl'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - Hbm2DDLExporterFacade

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HibernateMappingExporterExtension.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HibernateMappingExporterExtensionTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.HibernateMappingExporterExtensionTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.HibernateMappingExporterExtension'
- Add dependency on 'org.jboss.tools.hibernate.libs.freemarker.v_2_3'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - HibernateMappingExporterExtension

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HQLCodeAssistFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.HQLCodeAssistFacadeTest'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - HQLCodeAssistFacade

---

orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HQLCompletionProposalFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.HQLCompletionProposalFacadeTest'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - HQLCompletionProposalFacadeTest

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/QueryExporterFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/QueryExporterFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.QueryExporterFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.QueryExporterFacadeImpl'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - QueryExporterFacadeImpl

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/SchemaExportFacadeImpl.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/SchemaExportFacadeTest.java

- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.SchemaExportFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.SchemaExportFacadeImpl'

JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - SchemaExportFacade

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/VersionTest.java

- Update version identifiers of plugin 'org.jboss.tools.hibernate.orm.runtime.exp' to 5.4.20-SNAPSHOT
- Update version identifiers of test fragment 'org.jboss.tools.hibernatetools.orm.test' to 5.4.20-SNAPSHOT
- Update Maven dependency of plugin 'org.jboss.tools.hibernate.orm.runtime.exp' on Hibernate ORM to 6.2.0.CR1
- Update Maven dependency of plugin 'org.jboss.tools.hibernate.orm.runtime.exp' on Hibernate Tools to 6.2.0-SNAPSHOT
- Change plugin dependency of plugin 'org.jboss.tools.hibernate.orm.runtime.exp' on the jakarta persistence API to version 3.1.x

JBIDE-28628: Create an experimental Hibernate runtime that will use the new Hibernate Tools ORM to JBoss Tools adapter layer

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/util/GenericFacadeFactory.java

- Adapt the implementation of 'org.jboss.tools.hibernate.orm.runtime.exp.internal.util.GenericFacadeFactory' so that it accounts for proxy and wrapper arguments

JBIDE-28628: Create an experimental Hibernate runtime that will use te new Hibernate Tools ORM to JBoss Tools adapter layer

---

orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ColumnFacadeTest.java

- Change the version identifier in pom.xml to 6.1.7.Final
- Change the bundle classpath in 'META-INF/MANIFEST.MF' to include the proper jar files
- Adapt the tests in 'org.jboss.tools.hibernate.runtime.v_6_1.VersionTest' accordingly
- Change test case 'org.jboss.tools.hibernate.runtime.v_6_1.internal.ColumnFacadeTest#testGetSqlType()' to force setting the SQL type

JBIDE-28872: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_1 to version 6.1.7.Final

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryTest.java

- Override method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryImpl#createProperty(Object)' to throw a RuntimeException
- Adapt test method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryTest#testCreateProperty() according to the above change

JBIDE-28764: Implement and use the generic adapter for IProperty in the experimental Hibernate runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IDatabaseReader.java
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/ServiceImpl.java
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/util/NewFacadeFactory.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/util/NewFacadeFactoryTest.java

- Add new interface 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IDatabaseReader' with method 'collectDatabaseTables()'
- Add new test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.util.NewFacadeFactoryTest#testCreateDatabaseReader()'
- Add new implementation method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.util.NewFacadeFactory#createDatabaseReader(Properties,IReverseEngineeringStrategy)'
- Adapt the implementation of 'org.jboss.tools.hibernate.orm.runtime.exp.internal.ServiceImpl#collectDatabaseTables(Properties,IReverseEngineeringStrategy)'

JBIDE-28769: Implement and use the generic adapter for ITable in the experimental Hibernate runtime

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/ITypeFactoryTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/util/NewFacadeFactoryTest.java

- Adapt the tests of 'org.jboss.tools.hibernate.orm.runtime.exp.internal.ITypeFactoryTest' to the changes in the 'jbt' module
- Adapt test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.util.NewFacadeFactoryTest' to account for the changes in the 'jbt' module

JBIDE-28771: Implement and use the generic adapter for ITypeFactory in the experimental Hibernate runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryTest.java

- Adapt test method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryTest#testCreatePrimaryKey()' to check that 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryImpl#createPrimaryKey(Object)' throws an exception
- Implement method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryImpl#createPrimaryKey(Object)' to throw an exception

JBIDE-28763: Implement and use the generic adapter for IPrimaryKey in the experimental Hibernate runtime

---

orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/NewHibernateMappingFileWizard.java
orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IExportPOJODelegate.java

- Add new method 'org.jboss.tools.hibernate.runtime.spi.IExportPOJODelegate#exportPojo(Map<Object,Object>,Object,String)' with default implementation'

JBIDE-28758: Remove interface IPOJOClass and replace it by untyped Object

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IHibernateMappingExporterTest.java

- Initial creation of test class 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IHibernateMappingExporterTest'
- Add test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IHibernateMappingExporterTest#testConstruction()'

JBIDE-28976: Implement and use the generic adapter for IHibernateMappingExporter in the experimental Hibernate runtime

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IQueryExporterTest.java

- Adapt the test case setup of 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IQueryExporterTest' to take care of a change in the implementation of 'org.hibernate.tool.orm.jbt.wrp.WrapperFactory'

JBIDE-28755: Implement and use the generic adapter for IQueryExporter in the experimental Hibernate runtime

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IExporterTest.java

- Add new test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IExporterTest#testGetQueryExporter()'

JBIDE-28756: Implement and use the generic adapter for IExporter in the experimental Hibernate runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryTest.java

- Disable method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryImpl#createGenericExporter(Object' by making it throw a runtime exception
- Adapt test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryTest#testCreateGenericExporter()' accordingly

JBIDE-28774: Implement and use the generic adapter for IGenericExporter in the experimental Hibernate runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryImpl.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/FacadeFactoryTest.java

- Disable method 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryImpl#createHbm2DDLExporter(Object)' by making it throw a runtime exception
- Adapt test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.FacadeFactoryTest#testCreateHbm2DDLExporter()' accordingly

JBIDE-28754: Implement and use the generic adapter for IHbm2DDLExporter in the experimental Hibernate runtime

---

features/org.hibernate.eclipse.feature/feature.xml

- Add missing dependency on plugin 'org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_1'

JBIDE-29026: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_2 to version 6.2.4.Final

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IHQLCodeAssistTest.java

- Add new initial test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IHQLCodeAssistTest#testConstruction()'

JBIDE-28759: Implement and use the generic adapter for IHQLCodeAssist in the experimental Hibernate runtime

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/IQueryTest.java

- Create new initial test case 'org.jboss.tools.hibernate.orm.runtime.exp.internal.IQueryTest'

Implement and use the generic adapter for IQuery in the experimental Hibernate runtime

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.common/META-INF/MANIFEST.MF
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.common/build.properties
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.common/pom.xml

- Initial creation of plugin 'org.jboss.tools.hibernate.orm.runtime.common' that will hold the generic functionality

JBIDE-29047: Extract the generic functionality from the experimental runtime plugin

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/META-INF/MANIFEST.MF
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/build.properties
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/pom.xml
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_2/VersionTest.java

- Initial creation of new test fragment 'org.jboss.tools.hibernate.orm.runtime.v_6_2.test'

JBIDE-29046: Move the existing Hibernate 6.2 runtime plugin and make use of the new JBoss Tools adapter

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_2/IQueryTest.java

- Add new test class 'org.jboss.tools.hibernate.orm.runtime.v_6_2.IQueryTest'

 JBIDE-29046: Move the existing Hibernate 6.2 runtime plugin and make use of the new JBoss Tools adapter

---

orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3/plugin.properties
orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3/plugin.xml
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_3/VersionTest.java

- Contribute 'org.jboss.tools.hibernate.orm.runtime.v_6_3.ServiceImpl' to extension point 'org.jboss.tools.hibernate.runtime.spi.services' with version identifier '6.3 Preview'
- Add test case 'org.jboss.tools.hibernate.orm.runtime.v_6_3.VersionTest#testRuntimeVersion()'

JBIDE-29054: Create a Hibernate 6.3 runtime plugin

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/IArtifactCollectorTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/IExporterTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/IPersistentClassTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/ServiceImplTest.java

- Adapt some tests because of changes in the HT/JBT runtime bridge 
* IArtifactCollectorTest 
* IExporterTest 
* IPersistentClassTest

JBIDE-29162: Create a Hibernate runtime plugin for the 6.5 releases

---

orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_2/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_3/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_4.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_4/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_6.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_6/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_7_0.test/src/org/jboss/tools/hibernate/orm/runtime/v_7_0/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_5.test/src/org/jboss/tools/hibernate/runtime/v_5_5/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/ExportersPresenceTest.java
orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/ExportersPresenceTest.java

- Handle the case of 'org.hibernate.tool.hbm2x.POJOExporter'

JBIDE-29221: Make sure that the Exporter classes needed by plugin 'org.hibernate.eclipse.console' are visible and available
