- plugins/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/utils/PaneVisibilityEnabler.java
- plugins/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/utils/StateController.java
Migrate to Neon M3 development release. See http://git.eclipse.org/c/dali/webtools.dali.git/commit/common/plugins/org.eclipse.jpt.common.utility/src/org/eclipse/jpt/common/utility/internal/collection/CollectionTools.java?id=1d62c97e1dada43ee9a58bbc48f540ee34e8a51d for details.
> JBIDE-20976 Create and use Neon M3 target platform

- pom.xml
> [JBIDE-23192] - For JBIDE 4.4.2.AM1: Prepare for 4.4.2.AM1 / 10.2.0.AM1 [Hibernate]

- features/org.hibernate.eclipse.test.feature/feature.xml
- hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.v_4_0/pom.xml
- hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.v_5_3/pom.xml
- hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.v_5_5.1/pom.xml
- hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.v_5_5/pom.xml
- hibernate-search-plugins/org.jboss.tools.hibernate.search.runtime.v_5_7/pom.xml
- itests/org.jboss.tools.hibernate.ui.bot.test/pom.xml
- site/category.xml
- tests/org.hibernate.eclipse.console.test/pom.xml
- tests/org.hibernate.eclipse.jdt.ui.test/pom.xml
- tests/org.jboss.tools.hibernate.jpt.core.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.spi.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/pom.xml
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/pom.xml
Signed-off-by:...
clean up category.xml
Signed-off-by: nickboldt <nboldt@redhat.com>
> clean up category.xml

- docs/reference/en-US/reverseengineering.xml
- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewReverseEngineeringFileWizard.java
- plugins/org.hibernate.eclipse.mapper/dtd/hibernate-reverse-engineering-3.0.dtd
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/.classpath
- plugins/org.jboss.tools.hibernate.xml/src/org/jboss/tools/hibernate/xml/model/HibernateConstants.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/OverrideRepositoryFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/OverrideRepositoryFacadeTest.java
> JBIDE-25103: Use the correct URL for the Hibernate reverse engineering DTD

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractColumnFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IColumn.java
- plugins/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ColumnFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ColumnFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/FacadeFactoryImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ColumnFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/FacadeFactoryImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ColumnFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ColumnFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/.classpath
- plugins/org.jboss.tools.hibernate.ui/src/org/jboss/tools/hibernate/ui/view/OrmLabelProvider.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ColumnFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ColumnFacadeTest.java
> JBIDE-25107: Replace IColumn#getSqlType(IDialect,IConfiguration) by Column#getSqlType(Configuration)

- plugins/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
> JBIDE-25110: Complete the tests for IService#newDialect(Properties,Connection)

- plugins/org.jboss.tools.hibernate.ui/src/org/jboss/tools/hibernate/ui/view/OrmLabelProvider.java
> JBIDE-25114: Remove unused instance variable 'OrmLabelProvider#dialect'

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IConfiguration.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeTest.java
> JBIDE-25116: Remove unused method 'IConfiguration#getDialect()'

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractFacadeFactory.java
- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/IFacadeFactory.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryTest.java
> JBIDE-25117: Remove unused method 'IFacadeFactory#createDialect(Object)'

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
> JBIDE-25122: Cache the IMappings instance when creating IConviguration#createMappings()

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IConfiguration.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
> JBIDE-25123: Add method IConfiguration#addClass(IPersistentClass)

- plugins/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/ConfigurationActor.java
- tests/org.hibernate.eclipse.console.test/src/org/hibernate/eclipse/console/test/ConsoleConfigurationTest.java
> JBIDE-25124: Replace uses of IMapping#addClass(IPersistentClass) by IConfiguration#addClass(IPersistentClass)

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IConfiguration.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeTest.java
> JBIDE-25125: Remove unused method 'IConfiguration#createMappings()'

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeTest.java
> JBIDE-25132: Remove interface 'org.jboss.tools.hibernate.runtime.spi.IMappings' - Remove from AbstractConfigurationFacade

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractMappingsFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IMappings.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/MappingsFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/MappingsFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/MappingsFacadeImpl.java
> JBIDE-25132: Remove interface 'org.jboss.tools.hibernate.runtime.spi.IMappings' - Remove unused method IMappings#addClass(IPersistentClass)

- test-framework/org.jboss.tools.hibernate.reddeer/META-INF/MANIFEST.MF
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-25145 Added org.eclipse.ui.editors in RedDeer plugins Manifest

- plugins/org.jboss.tools.hibernate.ui/.gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Edit '.gitignore' to include generated '.classpath', '.project' and '.settings/'

- features/org.hibernate.search.eclipse.feature/.gitignore
> Remove the Eclipse related files from git - Edit 'org.hibernate.search.eclipse.feature/.gitignore' to include generated '.project' and '.settings/

- itests/.gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Create 'itests/.gitignore' to include generated '.project' and '.settings/'

- site/.gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Create 'site/.gitignore' to include generated '.project' and '.settings/'

- .gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Edit .gitignore to include '.project'

- docs/.gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Remove unneeded 'docs/.gitignore' file

- .gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Add entry '.classpath' to file '.gitignore'

- .gitignore
> JBIDE-25202: Remove the Eclipse related files from git - Add entry 'lib/' to file '.gitignore'

- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/HibernateMappingExporterFacadeTest.java
> JBIDE-25307: Use TemporaryFolder @Rule in the implementations of HibernateMappingExporterFacadeTest

- test-framework/org.jboss.tools.hibernate.reddeer/pom.xml
> JBIDE-25352: Remove excess groupId in org.jboss.tools.hibernate.reddeer

- itests/org.jboss.tools.hibernate.ui.bot.test/build.properties
> JBIDE-25373: Clean up 'build.properties' in 'org.jboss.tools.hibernate.ui.bot.test'

- plugins/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
> JBIDE-25391: Create 'PrimaryKey' object as part of 'Table' creation in the implementations of 'IService.newTable(String)'

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractTableFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/ITable.java
- tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/ConsoleConfigurationTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/TableFacadeTest.java
> JBIDE-25394: Remove unneeded occurrences of ITable#setPrimaryKey(IPrimaryKey)

- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IService.java
- plugins/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- tests/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/spi/internal/TestService.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
> JBIDE-25395: Remove unneeded method 'IService#newPrimaryKey()'

- tests/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/mapping/CUTMappingTest.java
> [JBIDE-25580] - Failing tests

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IConfiguration.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeTest.java
> JBIDE-25754: Remove unused method IConfiguration.getDefaultSchemaName()

- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractConfigurationFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IConfiguration.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ConfigurationFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ConfigurationFacadeTest.java
> JBIDE-25757: Remove unused method IConfiguration.getDefaultCatalogName()

- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/SessionFactoryFacadeTest.java
> JBIDE-25767: Remove unused imports from org.jboss.tools.hibernate.runtime.v_4_3.internal.SessionFactoryFacadeTest

- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/QueryFacadeTest.java
> JBIDE-25768: Replace uses of org.hibernate.Query with org.hibernate.query.Query

- features/org.hibernate.eclipse.feature/feature.xml
- plugins/org.jboss.tools.hibernate.libs.freemarker.v_2_3_23/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.libs.freemarker.v_2_3_23/build.properties
- plugins/org.jboss.tools.hibernate.libs.freemarker.v_2_3_23/pom.xml
- plugins/pom.xml
> JBIDE-25805: Add plugin 'org.jboss.tools.hibernate.libs.freemarker.v_2_3_23'

- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/FacadeFactoryImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/SchemaExportFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/SchemaExportFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryTest.java
> JBIDE-25809: Performing schema export does not work for latest Hibernate versions

- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/views/SchemaExportAction.java
- plugins/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractSchemaExportFacade.java
- plugins/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/ISchemaExport.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/SchemaExportFacadeImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/SchemaExportFacadeImpl.java
- tests/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/SchemaExportFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/SchemaExportFacadeTest.java
> JBIDE-25810: Remove the boolean arguments from IExportSchema#create(boolean, boolean)

- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java
> JBIDE-25690: Create a Runtime Plugin for Hibernate 5.3 - Properly implement version test

- test-framework/org.jboss.tools.hibernate.reddeer/META-INF/MANIFEST.MF
> [JBIDE-25970] - Adapt Hibernate for Photon

- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/utils/ClassLoaderHelper.java
- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/ProjectCompilerVersionChecker.java
- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationJavaClasspathTab.java
- plugins/org.hibernate.eclipse/src/org/hibernate/console/ConsoleConfigClassLoader.java
> JBIDE-25553: Cannot create Hibernate Console Configuration for projects with java 9

- tests/org.jboss.tools.hibernate.jpt.core.test/pom.xml
> JBIDE-25983: Temporarily disable failing tests of bundle 'org.jboss.tools.hibernate.jpt.core.test'

- plugins/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
- plugins/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- plugins/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/util/DummyMetadataBuildingContext.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/FacadeFactoryTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/HibernateMappingExporterFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/TableFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/TypeFacadeTest.java
- tests/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ValueFacadeTest.java
> JBIDE-25993: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.0.CR2

- itests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/PersistenceXMLFileTest.java
- itests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/ui/bot/test/factory/HibernateToolsFactory.java
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> Wait for persistence.xml file to appear

- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/utils/ClassLoaderHelper.java
- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/ProjectCompilerVersionChecker.java
- plugins/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationJavaClasspathTab.java
> JBIDE-26437: Make the Hibernate Tools work with Java 10 - Initial changes to make the tests run on Java 10 and Java 11

- features/org.hibernate.eclipse.feature/feature.xml
- plugins/org.jboss.tools.hibernate.libs.activation.v_1_2_0/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.libs.activation.v_1_2_0/build.properties
- plugins/org.jboss.tools.hibernate.libs.activation.v_1_2_0/pom.xml
- plugins/pom.xml
> JBIDE-26437: Make the Hibernate Tools work with Java 10 - Add plugin org.jboss.tools.hibernate.libs.activation.v_1_2_0

- features/org.hibernate.eclipse.feature/feature.xml
- plugins/org.jboss.tools.hibernate.libs.jaxb-api.v_2_3_0/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.libs.jaxb-api.v_2_3_0/build.properties
- plugins/org.jboss.tools.hibernate.libs.jaxb-api.v_2_3_0/pom.xml
- plugins/pom.xml
> JBIDE-26437: Make the Hibernate Tools work with Java 10 - Add plugin org.jboss.tools.hibernate.libs.jaxb-api.v_2_3_0

- features/org.hibernate.eclipse.feature/feature.xml
- plugins/org.jboss.tools.hibernate.libs.jaxb-core.v_2_3_0/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.libs.jaxb-core.v_2_3_0/build.properties
- plugins/org.jboss.tools.hibernate.libs.jaxb-core.v_2_3_0/pom.xml
- plugins/pom.xml
> JBIDE-26437: Make the Hibernate Tools work with Java 10 - Add plugin org.jboss.tools.hibernate.libs.jaxb-core.v_2_3_0

- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-26498 - coretests failing because of an hibernate dependency missing

- plugins/org.jboss.tools.hibernate.runtime.v_5_4/META-INF/MANIFEST.MF
- plugins/org.jboss.tools.hibernate.runtime.v_5_4/build.properties
- plugins/org.jboss.tools.hibernate.runtime.v_5_4/pom.xml
> JBIDE-26508: Update classmate version to 1.3.4 in org.jboss.tools.hibernate.runtime.v_5_4

- plugins/libs/pom.xml
- plugins/orm/pom.xml
- plugins/pom.xml
> JBIDE-26543: Reorganize plugins and test plugins in a more coherent module hierarchy - Create 'libs' and 'orm' module under 'plugins'

- plugins/pom.xml
- plugins/runtimes/pom.xml
> JBIDE-26543: Reorganize plugins and test plugins in a more coherent module hierarchy - Create 'runtimes' module under 'plugins'

- pom.xml
- search/plugin/core/pom.xml
- search/plugin/pom.xml
- search/pom.xml
> JBIDE-26543: Reorganize plugins and test plugins in a more coherent module hierarchy - Create module 'search/plugin/core'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/util/DummyMetadataDescriptor.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/util/DummyMetadataDescriptor.java
> JBIDE-26569: Cannot create hibernate config file for hibernate 5.3 and 5.4

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/META-INF/MANIFEST.MF
> JBIDE-26698: Hibernate 3.5 - Can’t open connection - Quick fix

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ExporterFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ExporterFacadeImpl.java
> JBIDE-26753: Reverse engineering wrongly overwrites the hibernate.cfg.xml file for hibernate 5.3 and 5.4

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/ConsoleConfigurationWizardPage.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizard.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizardPage.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationMainTab.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationTabGroup.java
> JBIDE-26755: Make the Hibernate version fixed on the create configuration console page of the create hibernate configuration file wizard

- README.md
I noticed the pull request link in the read me is dead so I updated it. It didn't seem worth making a JIRA ticket for.
> Corrected pull request help link in the readme.

- orm/plugin/core/org.hibernate.eclipse.jdt.ui/META-INF/MANIFEST.MF
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>
> JBIDE-26825: fix build

- orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/ConfigurationActor.java
- orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/NewHibernateMappingFileWizard.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/HibernateMappingExporterExtension.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/HibernateMappingExporterExtension.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/HibernateMappingExporterExtension.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ConfigurationFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/HibernateMappingExporterExtension.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/util/ConfigurationMetadataDescriptor.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ConfigurationFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/util/ConfigurationMetadataDescriptor.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/HibernateMappingExporterExtensionTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/HibernateMappingExporterFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/HibernateMappingExporterExtensionTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/HibernateMappingExporterFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/HibernateMappingExporterExtensionTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/HibernateMappingExporterFacadeTest.java
> JBIDE-23066: Generating hbm.xml files always happens using the 3.5 runtime

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/ProjectCompilerVersionChecker.java
> JBIDE-27437: Opening Hibernate console configuration fails for JDK 14

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/build.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/pom.xml
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial runtime plugin setup

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/META-INF/MANIFEST.MF
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/build.properties
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java
- orm/test/runtime/pom.xml
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial runtime test fragment setup

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - FacadeFactoryÌmpl extends AbstractFacadeFactory and implements IFacadeFactory

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testGetClassLoader()' and provide implementation

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateArtifactCollector()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/build.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateCfg2HbmTool()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateNamingStrategy()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateReverseEngineeringStrategy()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateOverrideRepository()'

- orm/test/core/org.jboss.tools.hibernate.orm.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testSetProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testSetProperties()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testAddFile()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testSetEntityResolver()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testGetEntityResolver()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testSetNamingStrategy()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testAddProperties()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/MetadataHelper.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/MetadataHelperTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add implementation of MetadataHelper#getMetadata(Configuration)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/hibernate.cfg.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/hibernate.properties
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/test/Foo.hbm.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/test/Foo.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testConfigure()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of JdbcMetadataConfiguration

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#getProperties()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#setProperties(Properties)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#setProperty(String,String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#getReverseEngineeringStrategy()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#getMetadata()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/META-INF/MANIFEST.MF
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/build.properties
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JdbcMetadataConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JdbcMetadataConfiguration#readFromJdbc()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeImpl#getMetadata()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeImpl#buildMappings()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateSessionFactory()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest# testBuildSessionFactory()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeImpl#getAddedClasses()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreatePersistentClass()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeImpl#addClass(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x release - Add 'ConfigurationFacadeImpl#getNamingStrategy()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testGetClassMapping()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest#testGetClassMappings()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateTable()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ConfigurationFacadeTest# testGetTableMappings()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of SchemaExportFacadeImpl

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SchemaExportFacadeImpl#setConfiguration(IConfiguration)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SchemaExportFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SchemaExportFacadeImpl#create()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'GenericExporterFacadeImpl#setFilePattern(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'GenericExporterFacadeImpl#setTemplateName(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'GenericExporterFacadeImpl#setForEach(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/GenericExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'GenericExporterFacadeImpl#getFilePattern()'

- .gitignore
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateQueryExporter()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest# testCreateHbm2DDLExporter()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of ExporterFacadeImpl

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptor.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptorTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of ConfigurationMetadataDescriptor

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptor.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptorTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of ConfigurationMetadataDescriptor#getProperties()

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptor.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/ConfigurationMetadataDescriptorTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of ConfigurationMetadataDescriptor#createMetadata()

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ExporterFacadeImpl#setConfiguration(IConfiguration)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ExporterFacadeImpl#setOutputDirectory(File)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ExporterFacadeImpl#setTemplatePath(String[])'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - 'ExporterFacadeTest#testStart()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest#testGetProperties()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest# testGetQueryExporter()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest#testSetCustomProperties()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ExporterFacadeTest#testSetOutput()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createExporter(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of class 'ClassMetadataFacadeImpl'

- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/eclipse/console/common/EntityPropertySource.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetMappedClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetPropertyValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetIdentifierPropertyName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetPropertyNames()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of TypeFacadeTest

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testGetName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testFromStringValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsEntityType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsOneToOne()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsCollectionType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsIntegerType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsArrayType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testIsInstanceOfPrimitiveType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testGetPrimitiveClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'TypeFacadeTest#testGetRole()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryImpl#testCreateType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testGetPropertyTypes()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'ClassMetadataFacadeTest#testIsInstanceOfAbstractEntityPersister()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EntityMetamodelFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EntityMetamodelFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Create implementation of EntityMetamodelFacadeImpl

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createEntityMetamodel(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ClassMetadataFacadeImpl#getEntityMetamodel()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractCriteriaFacade.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/ICriteria.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/CriteriaFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/CriteriaFacadeTest.java
> JBIDE-27526: Remove unused method ICriteria#createCriteria(String,String)

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/CriteriaFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Create initial implementation of CriteriaFacadeTest

- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/AbstractQueryPage.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/QueryPage.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/eclipse/console/common/HQLQueryPage.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/eclipse/console/common/JavaPage.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractCriteriaFacade.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/ICriteria.java
> JBIDE-27527: Change return type of ICriteria#list() to 'List<?>'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/CriteriaFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/CriteriaFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement class 'CriteriaFacadeImpl' and test class 'CriteriaFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createCriteria(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'FacadeFactoryTest#testCreateClassMetadata()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java
> Set up a runtime plugin for the Hibernate 6.0.x releases - Add 'SessionFactoryFacadeImpl#testGetAllClassMetadata()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/CollectionMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of test class 'CollectionMetadataFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#testCreateCollectionMetadata()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFactoryFacadeTest#testGetAllCollectionMetadata()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#testCreateSession()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFactoryFacadeTest#testOpenSession()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFactoryFacadeTest#testGetClassMetadata()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testGetSessionFactory()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ArtifactCollectorFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ArtifactCollectorFacadeTest'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'QueryFacadeTest#list()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'QueryFacadeTest#testSetMaxResults()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'QueryFacadeTest#testSetParameter()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'QueryFacadeTest#setParameterList(String,List<Object>,IType)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'QueryFacadeTest#testGetReturnTypes()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#testCreateQuery()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testCreateQuery()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testIsOpen()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testClose()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testContains()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'SessionFacadeTest#testCreateCriteria()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/Cfg2HbmToolFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of test class Cfg2HbmToolFacadeTest

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/Cfg2HbmToolFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'Cfg2HbmToolFacadeTest#testGetTagProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ClassMetadataFacadeTest#testHasIdentifierProperty()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ClassMetadataFacadeTest#testGetIdentifier()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetSqlTypeCode()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#testCreateConfiguration()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetSqlType()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#getLength()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetDefaultLength()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetPrecision()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetDefaultPrecision()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetScale()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetDefaultScale()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testIsNullable()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#testCreateValue()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testGetValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testIsUnique()'

- orm/plugin/core/org.jboss.tools.hibernate.ui/src/org/jboss/tools/hibernate/ui/view/OrmLabelProvider.java
> HBX-27550: Remove unused method OrmLabelProvider#getService()

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ColumnFacadeTest#testSetSqlType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ConfigurationFacadeTest#testGetProperties()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ConfigurationFacadeTest#testConfigureFile()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsSimpleValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetCollectionElement()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsOneToMany()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsManyToOne()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsOneToOne()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsMap()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsComponent()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsEmbedded()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsToOne()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetTable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetElement()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetCollectionTable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetTable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsList()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetIndex()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetTypeName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetComponentClassName()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createColumn(Object)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetColumnIterator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsTypeSpecified()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetCollectionTable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetKey()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetIndex()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetElementClassName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetTypeName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsDependantValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsAny()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsSet()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsPrimitiveArray()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsArray()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsIdentifierBag()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsBag()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetReferencedEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetEntityName()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImplTest#testCreateProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetPropertyIterator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testAddColumn()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetTypeParameters()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetForeignKeyName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetOwner()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetElement()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetParentProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetElementClassName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetKey()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testIsInverse()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testGetAssociatedClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetRole()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetReferencedEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'ValueFacadeTest#testSetAssociatedClass()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFactoryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFactoryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'TypeFactoryFacadeImpl' and the tests in 'TypeFactoryFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createTypeFactory()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryTest#'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TableFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement tests for ITable in TableFacadeTest

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement 'FacadeFactoryImpl#createReverseEngineeringStrategy(Object)'

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/LazyDatabaseSchemaWorkbenchAdapter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractJDBCReaderFacade.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IJDBCReader.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - IJDBCReader#readDatabaseSchema returns IDatabaseCollector

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/LazyDatabaseSchemaWorkbenchAdapter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImpl.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - Call IJDBCReader#setDatabaseCollector() at IJDBCReader creation time

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IJDBCReader.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImpl.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - Remove 'IJDBCReader#setDatabaseCollector(IDatabaseCollector)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractJDBCReaderFacade.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - Remove use of IDatabaseCollector from AbstractJDBCReaderFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractDatabaseReaderFacade.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractFacadeFactory.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - Rename AbstractJDBCReaderFacade to AbstractDatabaseReaderFacade

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/LazyDatabaseSchemaWorkbenchAdapter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IService.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/spi/internal/TestService.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImplTest.java
> JBIDE-27571: Merge functionality of IJDBCReader and IDatabaseCollector - Rename IService#newJDBCReader(...) to IService#newDatabaseReader(...)

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/workbench/LazyDatabaseSchemaWorkbenchAdapter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/DatabaseReaderFacadeImpl.java
> JBIDE-27579: Implement functionality of IDatabaseReader directly in IService - Reorganize LazyDatabaseSchemaWorkbenchAdapter

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImplTest.java
> JBIDE-27579: Implement functionality of IDatabaseReader directly in IService - Add tests for IService#collectDatabaseTables(...)

- orm/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/pom.xml
- orm/test/runtime/pom.xml
> JBIDE-27580: Update dependency of the runtime tests on H2 to version 1.4.200

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IService.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_5/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_0/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_4_3/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_0/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_2/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/spi/internal/TestService.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/ServiceImplTest.java
> JBIDE-27579: Implement functionality of IDatabaseReader directly in IService - Remove declaration and uses of IService#newDatabaseReader(...)

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetWrappedClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetDefaultSchema()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetDefaultCatalog()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetSessionFactoryName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/pom.xml
> JBIDE-27580: Invoke maven-clean-plugin in test fragments org.jboss.tools.hibernate.runtime.v_x_y.test

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetPass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetUser()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest# testGetURL()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetConnectionProvider()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetDataSource()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetDialect()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetHBM2DDLAuto()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/EnvironmentFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'EnvironmentFacadeTest#testGetDriver()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ForeignKeyFacadeTest#testColumnIterator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ForeignKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ForeignKeyFacadeTest#testContainsColumn()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implement FacadeFactoryTest#testCreatePOJOClass()

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of HibernateMappingExporterFacadeTest#testStart()

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of HibernateMappingExporterFacadeTest#testExportPOJO()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryImpl#createEnvironment()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryImpl#createHibernateMappingExporter(Object)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Initial implementation of HQLCompletionProposalFacadeTest

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetCompletion()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetReplaceEnd()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetSimpleName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetShortEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testGetProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testAliasRefKind()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testEntityNameKind()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testPropertyKind()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testKeywordKind()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HQLCompletionProposalFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'HQLCompletionProposalFacadeTest#testFunctionKind()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of FacadeFactoryTest#testCreateHQLCompletionProposal()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/JoinFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of FacadeFactoryTest#testCreateHQLCodeAssist()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of FacadeFactoryTest#testCreateJoin()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/INamingStrategy.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testCollectionTableName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> BIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testPropertyToColumnName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testTableName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testJoinKeyColumnName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testClassToTableName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/NamingStrategyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'NamingStrategyFacadeTest#testGetStrategyClassName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/OverrideRepositoryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'OverrideRepositoryFacadeTest#testAddFile()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/OverrideRepositoryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/OverrideRepositoryFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'OverrideRepositoryFacadeTest#testAddTableFilter()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testConstruction()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetClassName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetEntityName'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsRootClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetIdentifierProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testHasIdentifierProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsInstanceOfRootClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsInstanceOfSubclass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetSuperclass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetPropertyIterator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetTable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsAbstract()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractPersistentClassFacade.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetDiscriminator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetJoinIterator()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractPersistentClassFacade.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetVersion()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetClassName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetDiscriminatorValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetAbstract()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testAddProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsInstanceOfJoinedSubclass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetTable()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetKey()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetIdentifierProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetIdentifier()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetDiscriminator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetProxyInterfaceName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testSetLazy()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsCustomDeleteCallable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsCustomInsertCallable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsCustomUpdateCallable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsDiscriminatorValueNull()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsExplicitPolymorphism()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsForceDiscriminator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsLazy()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsLazyPropertiesCacheable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsMutable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsPolymorphic()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testIsVersioned()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetBatchSize()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetCustomSQLDelete()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetCustomSQLInsert()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
>  JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetCustomSQLUpdate()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetLoaderName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetOptimisticLockMode()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PersistentClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PersistentClassFacadeTest#testGetWhere()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PojoClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PojoClassFacadeTest#testGetQualifiedDeclarationName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testAddColumn()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testGetColumnSpan()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testContainsColumn()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testColumnIterator()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PrimaryKeyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PrimaryKeyFacadeTest#testGetName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testSetName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testSetPersistentClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsComposite()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetPersistentClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testClassIsPropertyClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testSetValue()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testSetCascade()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsBackRef()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsSelectable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsInsertable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsUpdateable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testGetCascade()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsLazy()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#testIsOptional()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'PropertyFacadeTest#ttestIsNaturalIdentifier()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryImpl#createQueryExporter(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/QueryExporterFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'QueryExporterFacadeTest#setFilename(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newDefaultConfiguration()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newAnnotationConfiguration()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JpaConfiguration#getPersistenceUnit()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JpaConfiguration#initialize()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JpaConfiguration#getMetadata()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JpaConfiguration#buildSessionFactory()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfiguration.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'JpaConfiguration#setProperties(Properties)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newJpaConfiguration(String,String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newSchemaExport(IConfiguration)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newHQLCodeAssist(IConfiguration)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#createExporter(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newArtifactCollector()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newTypeFactory()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newNamingStrategy(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newOverrideRepository()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newTableFilter()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newDefaultReverseEngineeringStrategy()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getReverseEngineeringStrategyClassName()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newCfg2HbmTool()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newProperty()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newTable(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newColumn(String)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newDialect(Properties,Connection)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getDriverManagerConnectionProviderClass()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getEnvironment()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newSimpleValue()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newRootClass()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newPrimitiveArray(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newArray(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newBag(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newList(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newMap(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newSet(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newManyToOne(ITable)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newOneToMany(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newOneToOne(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newSingleTableSubclass(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#newJoinedSubclass(IPersistentClass)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#isInitialized(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getClassLoader()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getClassWithoutInitializingProxy(Object)'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaMappingFileHelper.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaMappingFileHelperTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImpl#getJPAMappingFilePaths(String,EntityResolver)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SpecialRootClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'SpecialRootClassFacadeTest#testGetProperty()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SpecialRootClassFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SpecialRootClassFacadeTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'SpecialRootClassFacadeTest#testGetParentProperty()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryTest#testCreateSpecialRootClass()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ServiceImplTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'ServiceImplTest#newSpecialRootClass(IProperty)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
> JBIDE-27775: Use JUnit Jupiter instead of JUnit 4 - Switch test class 'org.jboss.tools.hibernate.runtime.v_6_0.internal.ClassMetadataFacadeTest'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/Cfg2HbmToolFacadeTest.java
> JBIDE-27775: Use JUnit Jupiter instead of JUnit 4 - Switch test class 'org.jboss.tools.hibernate.runtime.v_6_0.internal.Cfg2HbmToolFacadeTest'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/CollectionMetadataFacadeTest.java
> JBIDE-27775: Use JUnit Jupiter instead of JUnit 4 - Switch test class 'org.jboss.tools.hibernate.runtime.v_6_0.internal.CollectionMetadataFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
> JBIDE-27439: Set up a runtime plugin for the Hibernate 6.0.x releases - Implementation of 'FacadeFactoryImpl#createSessionFactory(Object)'

- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/node/IdentifierNode.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/node/PersistentCollectionNode.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/node/PropertyNode.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/node/TypeNode.java
> JBIDE-27823: Replace uses of 'org.jboss.tools.hibernate.runtime.spi.IType#getReturnedClass()' - Remove uses from plugin 'org.hibernate.eclipse'

- orm/plugin/ui/org.jboss.tools.hibernate.orm.ui/META-INF/MANIFEST.MF
- orm/plugin/ui/org.jboss.tools.hibernate.orm.ui/src/org/jboss/tools/hibernate/orm/ui/internal/RuntimesPreferencePage.java
> JBIDE-27827: Create a preference page to enable/disable contributed Hibernate runtime implementations - Create initial contents for preference page

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizard.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizardPage.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/CodeGenXMLFactory.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationMainTab.java
- orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/ConfigurationActor.java
- orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/NewHibernateMappingFileWizard.java
- orm/plugin/core/org.hibernate.eclipse.mapper/src/org/hibernate/eclipse/mapper/editors/StructuredTextViewerConfigurationUtil.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/ConfigurationFactory.java
- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/eclipse/console/common/HibernateExtension.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/HibernateJpaFactory.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/jpa2/HibernateJpaFactory2_0.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/wizard/GenerateInitWizardPage.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
- orm/plugin/ui/org.jboss.tools.hibernate.orm.ui/src/org/jboss/tools/hibernate/orm/ui/internal/RuntimesPreferencePage.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/HBMInfoExtractorTest.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/AnnotationsMappingTestHelper.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/CoreMappingTestHelper.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/JpaMappingTestHelper.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/MappingTestHelper.java
- orm/test/core/org.jboss.tools.hibernate.orm.test/src/org/jboss/tools/hibernate/orm/test/utils/TestConsoleConfigurationPreferences.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/spi/ServiceLookupTest.java
- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_4_0/src/org/jboss/tools/hibernate/search/HSearchServiceImpl.java
- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_3/src/org/jboss/tools/hibernate/search/HSearchServiceImpl.java
- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_5.1/src/org/jboss/tools/hibernate/search/HSearchServiceImpl.java
- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_5/src/org/jboss/tools/hibernate/search/HSearchServiceImpl.java
- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_7/src/org/jboss/tools/hibernate/search/HSearchServiceImpl.java
> JBIDE-27833: Rename class 'org.jboss.tools.hibernate.runtime.spi.ServiceLookup' to 'org.jboss.tools.hibernate.runtime.spi.RuntimeServiceManager'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
> JBIDE-27834: Transform class 'org.jboss.tools.hibernate.runtime.spi.RuntimeServiceManager' into a singleton - Make private helper methods non static

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
- orm/plugin/ui/org.jboss.tools.hibernate.orm.ui/src/org/jboss/tools/hibernate/orm/ui/internal/RuntimesPreferencePage.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManagerTest.java
> JBIDE-27827: Create a preference page to enable/disable contributed Hibernate runtime implementations - Save the default runtime version when changed

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManager.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.spi.test/src/org/jboss/tools/hibernate/runtime/spi/RuntimeServiceManagerTest.java
> Create a preference page to enable/disable contributed Hibernate runtime implementations - Implement method 'RuntimeServiceManager#restoreDefaults()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/build.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/plugin.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_5/plugin.xml
> JBIDE-27351: Set up a runtime plugin for the upcoming Hibernate 5.5.x releases - Contribute the 5.5 serviice to the platform

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/wizards/NewConfigurationWizardPage.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/CodeGenXMLFactory.java
- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/launch/ConsoleConfigurationMainTab.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/wizard/GenerateInitWizardPage.java
> JBIDE-27900: The configuration creation wizard should only offer a choice of the enabled runtimes

- orm/plugin/core/org.hibernate.eclipse.console/src/org/hibernate/eclipse/console/views/properties/HibernatePropertySourceProvider.java
> JBIDE-27901: Executing HQL from the HQL editor throws NPE

- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-27910: Add the Hibernate 5.5 runtime to the Hibernate feature

- itests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/reddeer/test/CreateJPAProjectTest.java
- itests/org.jboss.tools.hibernate.ui.bot.test/src/org/jboss/tools/hibernate/ui/bot/test/factory/JPAProjectFactory.java
- orm/test/util/org.jboss.tools.hibernate.reddeer/src/org/jboss/tools/hibernate/reddeer/wizard/JPAProjectWizardFirstPage.java
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27872 Fixes for CreateJPAProject test

- features/org.hibernate.eclipse.test.feature/feature.xml
> JBIDE-27913: Add test fragment 'org.jboss.tools.hibernate.runtime.v_5_5.test' to test feature 'org.hibernate.eclipse.test.feature'

- docs/contribute/contribute.md
> JBIDE-27952: Create a documentation page instructing possible contributors how to set up the development environment - Initial page creation

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ClassMetadataFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ConfigurationFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/FacadeFactoryTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/HibernateMappingExporterFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/PropertyFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFactoryFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ValueFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/JpaConfigurationTest.java
> JBIDE-27958: Review and Enable Disabled Tests after Updating to ORM 6.0.0-Alpha8 and Tools 6.0.0.Alpha4 - Cleanup

- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/META-INF/MANIFEST.MF
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/plugin.xml
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/HibernateJpaPlatform.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/JPAPostInstallFasetListener.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/context/orm/jpa2/HibernateOrmXml2_2Definition.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/context/persistence/JPA2_2.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/context/persistence/jpa2/Hibernate2_2PersistenceXmlContextNodeFactory.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/context/persistence/jpa2/Hibernate2_2PersistenceXmlDefinition.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/jpa2_2/HibernateJpa2_2PlatformFactory.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.core/src/org/jboss/tools/hibernate/jpt/core/internal/jpa2_2/HibernateJpa2_2PlatformProvider.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/META-INF/MANIFEST.MF
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/plugin.xml
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/HibernateJpa2_2PlatformUiProvider.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/jpa2/mapping/details/orm/Hibernate2_2OrmXmlUiDefinition.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/persistence/details/jpa2/HibernatePersistenceXml2_2UiDefinition.java
- orm/plugin/core/org.jboss.tools.hibernate.jpt.ui/src/org/jboss/tools/hibernate/jpt/ui/internal/platform/HibernateJpa2_2PlatformUiFactory.java
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>
> JBIDE-27426 Add Support for JPA 2.2

- common/plugin/lib/org.jboss.tools.hibernate.libs.jandex.v_2_4/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.jandex.v_2_4/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.jandex.v_2_4/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28014: Create a library plugin for JBoss Jandex 2.4

- orm/test/core/org.jboss.tools.hibernate.orm.test/pom.xml
> JBIDE-28016: Increase surefire.timeout property for test plugin 'org.jboss.tools.hibernate.orm.test'

- common/plugin/lib/org.jboss.tools.hibernate.libs.commons-collections4.v_4_4/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.commons-collections4.v_4_4/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.commons-collections4.v_4_4/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28037: Create a library plugin for Commons Collections4

- common/plugin/lib/org.jboss.tools.hibernate.libs.freemarker.v_2_3/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.freemarker.v_2_3/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.freemarker.v_2_3/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28042: Create a library plugin for Freemarker 2.3.x

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/internal/ReverseEngineeringSettingsFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/internal/ReverseEngineeringStrategyFacadeTest.java
> JBIDE-27986

- orm/pom.xml
- pom.xml
- search/pom.xml
> JBIDE-28079: Add 'tests' as a module in main pom.xml so that the updates of the versions are happening correctly

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_0/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_0/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_0/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28108: Create a library plugin for the Jakarta persistence API 3.0

- common/plugin/lib/org.jboss.tools.hibernate.libs.javassist.v_3_28/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.javassist.v_3_28/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28186: Create a library plugin for Javassist 3.28.x

- common/plugin/lib/org.jboss.tools.hibernate.libs.javassist.v_3_28/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.javassist.v_3_28/build.properties
> JBIDE-28186: Create a library plugin for Javassist 3.28.x - Fix build properties and plugin classpath

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_1/META-INF/MANIFEST.MF
> JBIDE-28092: Update the execution environment of the JBoss Tools plugins to Java 11 - Perform changes for org.jboss.tools.hibernate.runtime.v_5_1

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java
> JBIDE-28263: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.2.Final

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_4/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/VersionTest.java
> JBIDE-28274: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_4 to version 5.4.33.Final

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java
> JBIDE-28275: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.25.Final

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ConfigurationFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SchemaExportFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/ServiceImplTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SessionFactoryFacadeTest.java
> JBIDE-28083: Hibernate Java 17 compability - Reenable the disabled tests in 'org.jboss.tools.hibernate.runtime.v_5_0.test'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/META-INF/MANIFEST.MF
> JBIDE-28092: Update the execution environment of the JBoss Tools plugins to Java 11 - Perform changes for org.jboss.tools.hibernate.runtime.v_4_3.test

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/pom.xml
Add proper flags for v_4_3 runtime tests
> JBIDE-28083: Hibernate Java 17 compatibility

- pom.xml
> JBIDE-28289: Replace 'http' requests with 'https'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/HQLCompletionProposalFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/JoinFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/NamingStrategyFacadeTest.java
> JBIDE-28279: Improve the tests of the 4.3 runtime plugin - Add test class 'org.jboss.tools.hibernate.runtime.v_4_3.internal.NamingStrategyFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/MockDialect.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SessionFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/TypeFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/util/MockDialectTest.java
> JBIDE-28308: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_0 to version 6.0.0.Beta3

- orm/plugin/core/org.hibernate.eclipse/src/org/hibernate/console/ConfigurationFactory.java
> JBIDE-28312: Remove the transaction manager lookup in class 'org.hibernate.console.ConfigurationFactory'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/ConfigurationFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/SchemaExportFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/SessionFactoryFacadeTest.java
> JBIDE-28344: Improve the tests of the 3.5 runtime plugin - Disable failing tests

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform changes for 'org.jboss.tools.hibernate.runtime.v_3_6.test'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_3_6/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform changes for 'org.jboss.tools.hibernate.runtime.v_3_6'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/legacy/FloatType.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java
> JBIDE-28401: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_0 to version 6.0.0.CR2

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/build.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java
> JBIDE-28413: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.7.Final

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java
> JBIDE-28454: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.26.Final

- itests/org.jboss.tools.hibernate.ui.bot.test/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.ui.bot.test'

- common/plugin/lib/org.jboss.tools.hibernate.libs.transaction-api.v_1_2/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.transaction-api.v_1_2'

- common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_9/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_9'

- common/plugin/lib/org.jboss.tools.hibernate.libs.byte-buddy.v_1_11/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.byte-buddy.v_1_11'

- common/plugin/lib/org.jboss.tools.hibernate.libs.classmate.v_1_5/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.classmate.v_1_5'

- common/plugin/lib/org.jboss.tools.hibernate.libs.commons-collections4.v_4_4/META-INF/MANIFEST.MF
>  JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.commons-collections4.v_4_4'

- common/plugin/lib/org.jboss.tools.hibernate.libs.freemarker.v_2_3/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.freemarker.v_2_3'

- common/plugin/lib/org.jboss.tools.hibernate.libs.h2.v_1_4/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.h2.v_1_4'

- common/plugin/lib/org.jboss.tools.hibernate.libs.hibernate-commons-annotations.v_5_1/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.hibernate-commons-annotations.v_5_1'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-activation-api.v_2_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jakarta-activation-api.v_2_0'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_0'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-transaction-api.v_2_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jakarta-transaction-api.v_2_0'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-xml-bind-api.v_3_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jakarta-xml-bind-api.v_3_0'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jandex.v_2_4/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jandex.v_2_4'

- common/plugin/lib/org.jboss.tools.hibernate.libs.javassist.v_3_28/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.javassist.v_3_28'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jaxb.v_2_3/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jaxb.v_2_3'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jaxb.v_3_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jaxb.v_3_0'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jpa.v_2_2/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jpa.v_2_2'

- search/plugin/core/org.jboss.tools.hibernate.search/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/plugin.properties
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/plugin.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/VersionTest.java
> JBIDE-28464: Hibernate 6.0 should not anymore be presented as preview

- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_4_0/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search.runtime.v_4_0'

- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_3/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search.runtime.v_5_3'

- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_5/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search.runtime.v_5_5'

- search/plugin/runtime/org.jboss.tools.hibernate.search.runtime.v_5_5.1/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search.runtime.v_5_5.1'

- search/test/core/org.jboss.tools.hibernate.search.test/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.search.test'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SpecialRootClassFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_5.test/src/org/jboss/tools/hibernate/runtime/v_5_5/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/internal/SpecialRootClassFacadeTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/SpecialRootClassFacadeTest.java
> JBIDE-28473: Problem when closing the workspace after creating diagram with the Hibernate 6.0 runtime

- common/plugin/lib/org.jboss.tools.hibernate.libs.hibernate-commons-annotations.v_6_0/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.hibernate-commons-annotations.v_6_0/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.hibernate-commons-annotations.v_6_0/pom.xml
- common/plugin/lib/pom.xml
> JBIDE-28479: Create library plugin for versions 6.0.x of hibernate-commons-annotations

- common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28482: Create library plugin for versions 4.10 of antlr4-runtime

- itests/org.jboss.tools.hibernate.ui.bot.test/META-INF/MANIFEST.MF
> JBIDE-28489: Remove dependency on 'org.jboss.tools.jst.web.ui' from 'org.jboss.tools.hibernate.ui.bot.test'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jtidy.v_r8-20060801/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform change for 'org.jboss.tools.hibernate.libs.jtidy.v_r8-20060801'

- common/plugin/lib/org.jboss.tools.hibernate.libs.byte-buddy.v_1_12/build.properties
> JBIDE-28513: Create a library plugin for Byte Buddy 1.12 - Minor change to the build.properties file

- common/plugin/lib/org.jboss.tools.hibernate.libs.dom4j.v_2_1/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.dom4j.v_2_1/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.dom4j.v_2_1/pom.xml
- common/plugin/lib/pom.xml
- features/org.hibernate.eclipse.feature/feature.xml
> JBIDE-28522: Create a library plugin for Dom4J versions 2.1.x

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_3/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/VersionTest.java
Signed-off-by: blafond <blafond@redhat.com>
> JBIDE-28529: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_3 to version 5.3.27.Final

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/FacadeFactoryImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/TypeFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/FacadeFactoryTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add 'FacadeFactoryTest#testCreateType()' and implement 'FacadeFactoryImpl#createType(Object)'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/SpecialRootClassFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add 'SpecialRootClassFacadeTest#testIsInstanceOfSpecialRootClass()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/SpecialRootClassFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add 'SpecialRootClassFacadeTest#testGetProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/SpecialRootClassFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add 'SpecialRootClassFacadeTest#testGetParentProperty()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/Cfg2HbmToolFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add test class 'org.jboss.tools.hibernate.runtime.v_6_1.internal.Cfg2HbmToolFacadeTest'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ClassMetadataFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ClassMetadataFacadeTest#testGetEntityName()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ConfigurationFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ConfigurationFacadeTest#testGetProperty()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/META-INF/MANIFEST.MF
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ConfigurationFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ConfigurationFacadeTest#testGetMetadata()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ConfigurationFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ConfigurationFacadeTest#testGetClassMapping()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ColumnFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ColumnFacadeTest#testIsNullable()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ColumnFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'ColumnFacadeTest#testSetSqlType()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/CriteriaFacadeTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Add new test method 'CriteriaFacadeTest#testSetMaxResults()'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ServiceImplTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Implementation of new test method 'ServiceImplTest#testNewDefaultConfiguration()'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/build.properties
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java
> JBIDE-28549: Create a Runtime Plugin for Hibernate 6.1 - Implementation of new test class 'org.jboss.tools.hibernate.runtime.v_6_1.VersionTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/VersionTest.java
Signed-off-by: blafond <blafond@redhat.com>
> JBIDE-28618: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_6_1 to version 6.1.1.Finall

- orm/plugin/core/org.jboss.tools.hibernate.xml/META-INF/MANIFEST.MF
> JBIDE-28092: Update execution environment to Java 11 - Perform changefor plugin 'org.jboss.tools.hibernate.xml'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java
Signed-off-by: blafond <blafond@redhat.com>
> JBIDE-28773: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.14.Final

- orm/plugin/core/org.hibernate.eclipse.mapper/src/org/hibernate/eclipse/mapper/editors/reveng/TypeMappingView.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/ColumnFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.common/src/org/jboss/tools/hibernate/runtime/common/AbstractColumnFacade.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.spi/src/org/jboss/tools/hibernate/runtime/spi/IColumn.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/jboss/tools/hibernate/runtime/v_6_0/internal/ColumnFacadeImpl.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/jboss/tools/hibernate/runtime/v_6_1/internal/ColumnFacadeImpl.java
> JBIDE-28800: IColumn#getLength() needs to return a long value

- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/internal/ISessionFactoryTest.java
> JBIDE-28768: Implement and use the generic adapter for ISessionFactory in the experimental Hibernate runtime

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/bin/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/bin/pom.xml
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/pom.xml
- orm/plugin/runtime/pom.xml
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - Initial setup of 'org.jboss.tools.hibernate.runtime.v.6.2'

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/META-INF/MANIFEST.MF
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/build.properties
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_1/DummyTest.java
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - Initial setup of test fragment 'org.jboss.tools.hibernate.runtime.v.6.2.test'

- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_1/META-INF/MANIFEST.MF
- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_1/build.properties
- common/plugin/lib/org.jboss.tools.hibernate.libs.jakarta-persistence-api.v_3_1/pom.xml
- common/plugin/lib/pom.xml
> JBIDE-28843: Create a library plugin for the Jakarta persistence API version 3.1.x

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/Cfg2HbmToolFacadeTest.java
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.Cfg2HbmToolFacadeTest'

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ClassMetadataFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ClassMetadataFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ClassMetadataFacadeTest'
- Implement method 'ClassMetadataFacadeImpl#getTuplizerPropertyValue(Object,int)'
- Add dependency on 'org.jboss.tools.hibernate.libs.antlr4-runtime.v_4_10'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ClassMetadataFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/CollectionMetadataFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.CollectionMetadataFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - CollectionMetadataFacadeTest

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ConfigurationFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/META-INF/MANIFEST.MF
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ConfigurationFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ConfigurationFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.ConfigurationFacadeImpl'
- Change dependency from 'org.jboss.tools.hibernate.libs.h2.v_2_1' to 'org.jboss.tools.hibernate.libs.h2.v_1_4'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ConfigurationFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ColumnFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ColumnFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ColumnFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.ColumnFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ColunmFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/CriteriaFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/CriteriaFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.CriteriaFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.CriteriaFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - CriteriaFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/EnvironmentFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/EnvironmentFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.EnvironmentFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.EnvironmentFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - EnvironmentFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ExporterFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ExporterFacadeTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.ExporterFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ExporterFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HibernateMappingExporterFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/HibernateMappingExporterFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.HibernateMappingExporterFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.HibernateMappingExporterFacade'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - HibernateMappingExporterFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/JoinFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.JoinFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - JoinFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/NamingStrategyFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.NamingStrategyFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - NamingStrategyFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/OverrideRepositoryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/OverrideRepositoryFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.OverrideRepositoryFacadeTest'
- Add implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.OverrideRepositoryFacadeImpl'
- Add dependency on 'org.jboss.tools.hibernate.libs.commons-collections4.v_4_4'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - OverrideRepositoryFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/PersistentClassFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.PersistentClassFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - PersistentClassFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/PojoClassFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.PojoClassFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - PojoClassFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/PrimaryKeyFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.PrimaryKeyFacade'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - PrimaryKeyFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/QueryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/QueryFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.QueryFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.QueryFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - QueryFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ReverseEngineeringSettingsFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ReverseEngineeringSettingsFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ReverseEngineeringSettingsFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ReverseEngineeringStrategyFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ReverseEngineeringStrategyFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ReverseEngineeringStrategyFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.ReverseEngineeringStrategyFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ReverseEngineeringStrategyFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/SessionFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.SessionFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - SessionFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/SpecialRootClassFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.SpecialRootClassFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - SpecialRootClassFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TableFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.TableFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - TableFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TableFilterFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.TableFilterFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - TableFilterFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TypeFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TypeFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.TypeFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.TypeFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - TypeFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_2/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TypeFactoryFacadeImpl.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/TypeFactoryFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.TypeFactoryFacadeTest'
- Complete implementation class 'org.jboss.hibernate.runtime.v_6_2.internal.TypeFactoryFacadeImpl'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - TypeFactoryFacade

- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_2.test/src/org/jboss/tools/hibernate/runtime/v_6_2/internal/ValueFacadeTest.java
- Add test class 'org.jboss.hibernate.runtime.v_6_2.internal.ValueFacadeTest'
> JBIDE-28836: Create a plugin for the Hibernate 6.2.x runtimes - ValueFacade

- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_5_6/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/VersionTest.java
> JBIDE-28871: Update hibernate tools dependency of org.jboss.tools.hibernate.runtime.v_5_6 to version 5.6.15.Final

- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/META-INF/MANIFEST.MF
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.exp/pom.xml
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.exp.test/src/org/jboss/tools/hibernate/orm/runtime/exp/VersionTest.java
- Update ORM dependency to version 6.2.0.CR3
> JBIDE-28628: Create an experimental Hibernate runtime that will use the new Hibernate Tools ORM to JBoss Tools adapter layer

- orm/plugin/core/org.hibernate.eclipse.jdt.ui/src/org/hibernate/eclipse/jdt/ui/wizards/ConfigurationActor.java
- Set a dummy table when creating a simple value before adding a column
> New Hibernate Mapping File Wizard results in an exception

- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.common/src/org/jboss/tools/hibernate/orm/runtime/common/IFacade.java
- Add new interface 'org.jboss.tools.hibernate.orm.runtime.common.IFacade'
> JBIDE-29047: Extract the generic functionality from the experimental runtime plugin

- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_2/IConfigurationTest.java
- Add new test class 'org.jboss.tools.hibernate.orm.runtime.v_6_2.IConfigurationTest"
> JBIDE-29046: Move the existing Hibernate 6.2 runtime plugin and make use of the new JBoss Tools adapter

- features/org.hibernate.eclipse.test.feature/feature.xml
- features/org.jboss.tools.hibernate.orm.runtime.feature/feature.xml
- orm/plugin/runtime/pom.xml
- orm/test/runtime/pom.xml
- Add module 'org.jboss.tools.hibernate.orm.runtime.v_6_3' to the runtime plugins
- Add plugin 'org.jboss.tools.hibernate.orm.runtime.v_6_3' to the feature 'org.jboss.tools.hibernate.orm.runtime.feature'
- Add module 'org.jboss.tools.hibernate.orm.runtime.v_6_3.test' to the runtime test fragments
- Add fragment 'org.jboss.tools.hibernate.orm.runtime.v_6_3.test' to the feature 'org.hibernate.eclipse.test.feature'
> JBIDE-29054: Create a Hibernate 6.3 runtime plugin

- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_4.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_4/ServiceImplTest.java
- Add method 'ServiceImplTest#beforeAll()' to make sure the tests run also in Eclipse
> JBIDE-29093: Create a Hibernate runtime plugin for the 6.4 releases

- features/org.hibernate.eclipse.test.feature/feature.xml
- features/org.jboss.tools.hibernate.orm.runtime.feature/feature.xml
- orm/plugin/runtime/pom.xml
- orm/test/runtime/pom.xml
- Include the 6.5 runtime plugin and test fragment in the main build and in the runtime and test features
> JBIDE-29162: Create a Hibernate runtime plugin for the 6.5 releases

- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_4/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_6/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.orm.runtime.v_7_0/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_0/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/plugin/runtime/org.jboss.tools.hibernate.runtime.v_6_1/src/org/hibernate/tool/hbm2x/DAOExporter.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_2.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_2/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_3.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_3/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_4.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_4/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_5.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_5/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_6_6.test/src/org/jboss/tools/hibernate/orm/runtime/v_6_6/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.orm.runtime.v_7_0.test/src/org/jboss/tools/hibernate/orm/runtime/v_7_0/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_5.test/src/org/jboss/tools/hibernate/runtime/v_3_5/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_3_6.test/src/org/jboss/tools/hibernate/runtime/v_3_6/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_0.test/src/org/jboss/tools/hibernate/runtime/v_4_0/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_4_3.test/src/org/jboss/tools/hibernate/runtime/v_4_3/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_0.test/src/org/jboss/tools/hibernate/runtime/v_5_0/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_1.test/src/org/jboss/tools/hibernate/runtime/v_5_1/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_2.test/src/org/jboss/tools/hibernate/runtime/v_5_2/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_3.test/src/org/jboss/tools/hibernate/runtime/v_5_3/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_4.test/src/org/jboss/tools/hibernate/runtime/v_5_4/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_5.test/src/org/jboss/tools/hibernate/runtime/v_5_5/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_5_6.test/src/org/jboss/tools/hibernate/runtime/v_5_6/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_0.test/src/org/jboss/tools/hibernate/runtime/v_6_0/ExportersPresenceTest.java
- orm/test/runtime/org.jboss.tools.hibernate.runtime.v_6_1.test/src/org/jboss/tools/hibernate/runtime/v_6_1/ExportersPresenceTest.java
- Handle the case of 'org.hibernate.tool.hbm2x.DAOExporter'
> JBIDE-29221: Make sure that the Exporter classes needed by plugin 'org.hibernate.eclipse.console' are visible and available
